// @ts-nocheck
// eslint-disable
/**
 * ---------------------------------------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------------------------------------
 * */

import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin(() => {
  const router = useRouter();
  const route = useRoute();
  const routesNames = {
    index: 'index',
    parentSlug: 'parent-slug',
    parentFooBar: 'parent-foo-bar',
    id: {
      slug: { articles: 'parent-id-slug-articles', index: 'parent-id-slug' },
      index: 'parent-id',
      posts: 'parent-id-posts',
    },
    parent: 'parent',
    parentTestOptional: 'parent-test-optional',
  };

  return {
    provide: {
      typedRouter: router as TypedRouter,
      typedRoute: route as TypedRoute,
      routesNames,
    },
  };
});
