packages:
  - test/fixtures/simple
  - test/fixtures/complex
  - test/fixtures/withOptions
  - docs

catalog:
  '@intlify/core-base': 11.2.8
  '@intlify/message-compiler': 11.2.8
  '@intlify/shared': 11.2.8
  '@intlify/vue-i18n-bridge': 1.1.0
  '@intlify/vue-router-bridge': 1.1.0
  '@nuxt/content': 3.11.2
  '@nuxt/devtools': 3.1.1
  '@nuxt/kit': 4.3.1
  '@nuxt/module-builder': 1.0.2
  '@nuxt/schema': 4.3.1
  '@nuxt/test-utils': 4.0.0
  '@nuxtjs/i18n': 10.2.3
  '@playwright/test': ^1.58.2
  '@types/lodash-es': 4.17.12
  '@types/node': 25.2.3
  '@vue/test-utils': 2.4.6
  better-sqlite3: ^12.6.2
  nuxt: 4.3.1
  playwright: ^1.58.2
  prettier: 3.8.1
  typescript: 5.9.3
  vitest: 3.2.1
  vue: 3.5.28
  vue-eslint-parser: 10.2.0
  vue-i18n: 11.2.8
  vue-router: 5.0.2
  vue-tsc: 3.2.4

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@types/node'

onlyBuiltDependencies:
  - '@intlify/vue-i18n-bridge'
  - '@intlify/vue-router-bridge'
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
