export const watermarkTemplate = `
  // @ts-nocheck
  // eslint-disable
  /** 
  * ---------------------------------------------------
  * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
  * ---------------------------------------------------
  * */
 
`;
