globalThis.entryURL = import.meta.url;import 'unenv/runtime/polyfill/fetch.node';
import 'http';
import 'https';
import 'destr';
export { s as default } from './chunks/nitro/server.mjs';
import 'h3';
import 'ohmyfetch';
import 'unenv/runtime/fetch/index';
import 'ufo';
import 'defu';
