/** Generated by nuxt-typed-router. Do not modify */
export const routerPagesNames = {
  activate: 'activate',
  index: 'index',
  childOne: {
    childOneChildOneSubOne: 'parent-child-one-child-one-sub-one',
    user: { index: 'parent-child-one-child-one-sub-one-user' },
    childOneChildOneSubTwo: 'parent-child-one-child-one-sub-two',
    index: 'parent-child-one',
  },
  childTwo: {
    childTwoId: 'parent-child-two-id',
    childTwoChildOneSubOne: 'parent-child-two-child-one-sub-one',
    index: 'parent-child-two',
    childTwoNameName: 'parent-child-two-name-name',
  },
  rootPage: 'rootPage',
};

export type TypedRouteList =
  | 'activate'
  | 'index'
  | 'parent-child-one-child-one-sub-one'
  | 'parent-child-one-child-one-sub-one-user'
  | 'parent-child-one-child-one-sub-two'
  | 'parent-child-one'
  | 'parent-child-two-id'
  | 'parent-child-two-child-one-sub-one'
  | 'parent-child-two'
  | 'parent-child-two-name-name'
  | 'rootPage';

export type TypedRouteParams = {
  'parent-child-two-id': {
    id?: string | number;
  };
  'parent-child-two-name-name': {
    name?: string | number;
  };
};

import { RouteLocationNormalized } from 'vue-router';

interface TypedRouterFnParams<T extends TypedRouteList> extends RouteLocationNormalized {
  name: T;
}

export function typedRouter<T extends TypedRouteList>(route: TypedRouterFnParams<T>) {}
